name: bot_interceptor
description: Fighttech Flutter Bot Interceptor
version: 0.0.3
homepage: https://github.com/FightTech-VN/bot_interceptor

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  dio: ^4.0.6
  bot_interceptor:
    path: ../