name: bot_interceptor
description: Fighttech Flutter Bot Interceptor
version: 0.1.33
homepage: https://github.com/FightTech-VN/bot_interceptor

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dart_telegram_bot: ^1.0.0
  dio: ^5.1.2
  uuid: ^3.0.7

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
