name: bot_interceptor
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/FightTech-VN/bot_interceptor

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dart_telegram_bot: ^0.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
