name: bot_interceptor
description: Fighttech Flutter Bot Interceptor
version: 0.0.17
homepage: https://github.com/FightTech-VN/bot_interceptor

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  dart_telegram_bot: ^1.0.0
  dio: ^4.0.6
  uuid: ^3.0.6

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
